In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/SAMPLE.csv")
df

    sl No name              college    hsc  SSLC  arrears  cmark
0     NaN  NaN                  NaN    NaN   NaN      NaN    NaN
1     1.0   A1                 IITM  89.90  92.6      0.0   95.0
2     2.0   A2      ANNA UNIVERSITY  76.80  77.9      3.0    NaN
3     3.0   A3      ANNA UNIVERSITY    NaN  85.6      6.0   99.0
4     4.0   A4  ANAMALAI UNIVERSITY  92.50  94.6      1.0   76.0
5     5.0   A5                  NaN  79.30  65.0      2.0   89.0
6     6.0   A6                  SRM  99.80  88.1      0.0   89.6
7     7.0   A7             SAVEETHA  91.80   NaN      7.0   78.3
8     8.0   A8             SAVEETHA  99.80  65.8     66.0   77.5
9    56.0  A34             SAVEETHA  99.80  99.8      5.0   77.5
10    3.0   A3      ANNA UNIVERSITY    NaN  85.6      6.0   99.0
11    NaN  NaN                  NaN    NaN   NaN      NaN    NaN
12    NaN  NaN                  NaN    NaN   NaN      NaN    NaN
13    9.0   A9  ANAMALAI UNIVERSITY  98.70  91.0      2.0   76.0
14   10.0   AD               fogjof  56.00   9.0      NaN    2.0
15   11.0  A10                 IITM  94.00  77.6      1.0   75.0
16   12.0  A11                  NaN  88.20   NaN      2.0   72.0
17   13.0  A12            dhgvuicbh  78.90  84.9      3.0   83.0
18   14.0  A13                  SRM  86.90  97.0     33.0   92.0
19    3.0   A3      ANNA UNIVERSITY  88.39  85.6      6.0   99.0

In [4]:
df.dropna()

    sl No name              college    hsc  SSLC  arrears  cmark
1     1.0   A1                 IITM  89.90  92.6      0.0   95.0
4     4.0   A4  ANAMALAI UNIVERSITY  92.50  94.6      1.0   76.0
6     6.0   A6                  SRM  99.80  88.1      0.0   89.6
8     8.0   A8             SAVEETHA  99.80  65.8     66.0   77.5
9    56.0  A34             SAVEETHA  99.80  99.8      5.0   77.5
13    9.0   A9  ANAMALAI UNIVERSITY  98.70  91.0      2.0   76.0
15   11.0  A10                 IITM  94.00  77.6      1.0   75.0
17   13.0  A12            dhgvuicbh  78.90  84.9      3.0   83.0
18   14.0  A13                  SRM  86.90  97.0     33.0   92.0
19    3.0   A3      ANNA UNIVERSITY  88.39  85.6      6.0   99.0

In [5]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [6]:
df.duplicated().sum()

3

In [10]:
df.drop_duplicates()

    sl No name              college    hsc  SSLC  arrears  cmark
0     NaN  NaN                  NaN    NaN   NaN      NaN    NaN
1     1.0   A1                 IITM  89.90  92.6      0.0   95.0
2     2.0   A2      ANNA UNIVERSITY  76.80  77.9      3.0    NaN
3     3.0   A3      ANNA UNIVERSITY    NaN  85.6      6.0   99.0
4     4.0   A4  ANAMALAI UNIVERSITY  92.50  94.6      1.0   76.0
5     5.0   A5                  NaN  79.30  65.0      2.0   89.0
6     6.0   A6                  SRM  99.80  88.1      0.0   89.6
7     7.0   A7             SAVEETHA  91.80   NaN      7.0   78.3
8     8.0   A8             SAVEETHA  99.80  65.8     66.0   77.5
9    56.0  A34             SAVEETHA  99.80  99.8      5.0   77.5
13    9.0   A9  ANAMALAI UNIVERSITY  98.70  91.0      2.0   76.0
14   10.0   AD               fogjof  56.00   9.0      NaN    2.0
15   11.0  A10                 IITM  94.00  77.6      1.0   75.0
16   12.0  A11                  NaN  88.20   NaN      2.0   72.0
17   13.0  A12            dhgvuicbh  78.90  84.9      3.0   83.0
18   14.0  A13                  SRM  86.90  97.0     33.0   92.0
19    3.0   A3      ANNA UNIVERSITY  88.39  85.6      6.0   99.0

In [11]:
df.drop_duplicates(keep="last")

    sl No name              college    hsc  SSLC  arrears  cmark
1     1.0   A1                 IITM  89.90  92.6      0.0   95.0
2     2.0   A2      ANNA UNIVERSITY  76.80  77.9      3.0    NaN
4     4.0   A4  ANAMALAI UNIVERSITY  92.50  94.6      1.0   76.0
5     5.0   A5                  NaN  79.30  65.0      2.0   89.0
6     6.0   A6                  SRM  99.80  88.1      0.0   89.6
7     7.0   A7             SAVEETHA  91.80   NaN      7.0   78.3
8     8.0   A8             SAVEETHA  99.80  65.8     66.0   77.5
9    56.0  A34             SAVEETHA  99.80  99.8      5.0   77.5
10    3.0   A3      ANNA UNIVERSITY    NaN  85.6      6.0   99.0
12    NaN  NaN                  NaN    NaN   NaN      NaN    NaN
13    9.0   A9  ANAMALAI UNIVERSITY  98.70  91.0      2.0   76.0
14   10.0   AD               fogjof  56.00   9.0      NaN    2.0
15   11.0  A10                 IITM  94.00  77.6      1.0   75.0
16   12.0  A11                  NaN  88.20   NaN      2.0   72.0
17   13.0  A12            dhgvuicbh  78.90  84.9      3.0   83.0
18   14.0  A13                  SRM  86.90  97.0     33.0   92.0
19    3.0   A3      ANNA UNIVERSITY  88.39  85.6      6.0   99.0

In [12]:
df.drop_duplicates(keep="first")

    sl No name              college    hsc  SSLC  arrears  cmark
0     NaN  NaN                  NaN    NaN   NaN      NaN    NaN
1     1.0   A1                 IITM  89.90  92.6      0.0   95.0
2     2.0   A2      ANNA UNIVERSITY  76.80  77.9      3.0    NaN
3     3.0   A3      ANNA UNIVERSITY    NaN  85.6      6.0   99.0
4     4.0   A4  ANAMALAI UNIVERSITY  92.50  94.6      1.0   76.0
5     5.0   A5                  NaN  79.30  65.0      2.0   89.0
6     6.0   A6                  SRM  99.80  88.1      0.0   89.6
7     7.0   A7             SAVEETHA  91.80   NaN      7.0   78.3
8     8.0   A8             SAVEETHA  99.80  65.8     66.0   77.5
9    56.0  A34             SAVEETHA  99.80  99.8      5.0   77.5
13    9.0   A9  ANAMALAI UNIVERSITY  98.70  91.0      2.0   76.0
14   10.0   AD               fogjof  56.00   9.0      NaN    2.0
15   11.0  A10                 IITM  94.00  77.6      1.0   75.0
16   12.0  A11                  NaN  88.20   NaN      2.0   72.0
17   13.0  A12            dhgvuicbh  78.90  84.9      3.0   83.0
18   14.0  A13                  SRM  86.90  97.0     33.0   92.0
19    3.0   A3      ANNA UNIVERSITY  88.39  85.6      6.0   99.0

In [13]:
df.drop_duplicates(keep=False)

    sl No name              college    hsc  SSLC  arrears  cmark
1     1.0   A1                 IITM  89.90  92.6      0.0   95.0
2     2.0   A2      ANNA UNIVERSITY  76.80  77.9      3.0    NaN
4     4.0   A4  ANAMALAI UNIVERSITY  92.50  94.6      1.0   76.0
5     5.0   A5                  NaN  79.30  65.0      2.0   89.0
6     6.0   A6                  SRM  99.80  88.1      0.0   89.6
7     7.0   A7             SAVEETHA  91.80   NaN      7.0   78.3
8     8.0   A8             SAVEETHA  99.80  65.8     66.0   77.5
9    56.0  A34             SAVEETHA  99.80  99.8      5.0   77.5
13    9.0   A9  ANAMALAI UNIVERSITY  98.70  91.0      2.0   76.0
14   10.0   AD               fogjof  56.00   9.0      NaN    2.0
15   11.0  A10                 IITM  94.00  77.6      1.0   75.0
16   12.0  A11                  NaN  88.20   NaN      2.0   72.0
17   13.0  A12            dhgvuicbh  78.90  84.9      3.0   83.0
18   14.0  A13                  SRM  86.90  97.0     33.0   92.0
19    3.0   A3      ANNA UNIVERSITY  88.39  85.6      6.0   99.0